name: CI

on:
  push:
  pull_request:

jobs:
  run-ci:
    name: Run

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: soap

      - name: Install dependencies
        run: composer install --prefer-source --no-interaction --dev

      - name: Run tests
        run: composer test
